name: Generate Profile Assets

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
    - master
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: generate-github-profile-3d-contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: almonzeir
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: almonzeir
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-neon.svg?color_snake=#00f260&color_dots=#161b22,#0e4429,#006d32,#26a641,#00f260
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move 3d contrib to dist
        run: |
          mkdir -p dist
          cp -r profile-3d-contrib/*.svg dist/ || true

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
